spring.application.name=spring-ai-mcp-tools
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.springai=DEBUG
logging.level.org.springframework.ai.mcp.server.common.autoconfigure=INFO

# MCP Server Configuration
spring.ai.mcp.server.name=spring-ai-mcp-tools
spring.ai.mcp.server.request-timeout=1h
spring.ai.mcp.server.protocol=STATELESS
spring.ai.mcp.server.port=8080